version: '3'

services:
  queue:
    image: nats/queue:0.0.1
    command: ["-nats=nats:4222", "-jaeger=http://jaeger:14268", "-rabbit=amqp://guest:guest@rabbit:5672/"]
    restart: always
    depends_on:
      - nats
      - rabbit 
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - queue

